steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [
      'clean',
      'package', 
      'jib:build',
      '-DskipTests',
      '-Djib.to.image=us-central1-docker.pkg.dev/bigquery-antipattern-test/bigquery-antipattern-tool/$BUILD_ID'
    ] 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 
      'jobs', 
      'create',
      'bigquery-antipattern-tool', # Replace with your Cloud Run service name
      '--image=us-central1-docker.pkg.dev/bigquery-antipattern-test/bigquery-antipattern-tool/$BUILD_ID', 
      '--max-retries=3',
      '--task-timeout=15m',
      '--args=--input_bq_table',
      '--args=bigquery-antipattern-test.antipattern_test_data.input_data',
      '--region=us-central1',
      '--service-account=bq-antipattern-cloud-run-sa@bigquery-antipattern-test.iam.gserviceaccount.com'
    ]

options:
  logging: CLOUD_LOGGING_ONLY



