steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [
      'clean',
      'package', 
      'jib:build',
      '-DskipTests',
      '-Djib.to.image=us-central1-docker.pkg.dev/bigquery-antipattern-test/bigquery-antipattern-tool/$BUILD_ID'
    ] 
  # - name: 'gcr.io/cloud-builders/gcloud' ##
  #   args: [
  #     'run', 
  #     'jobs', 
  #     'create',
  #     'bigquery-antipattern-tool', # Replace with your Cloud Run service name
  #     '--image=us-central1-docker.pkg.dev/bigquery-antipattern-test/bigquery-antipattern-tool/$BUILD_ID', 
  #     '--max-retries=3',
  #     '--task-timeout=15m',
  #     '--args=--input_bq_table',
  #     '--args=bigquery-antipattern-test.antipattern_test_data.input_data',
  #     '--args=--output_table',
  #     '--args=bigquery-antipattern-test.antipattern_test_data.output_data',
  #     '--region=us-central1',
  #     '--service-account=bq-antipattern-cloud-run-sa@bigquery-antipattern-test.iam.gserviceaccount.com'
  #   ]
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: [
  #     'run', 
  #     'jobs',
  #     'execute',
  #     'bigquery-antipattern-tool',
  #     '--region=us-central1'
  #   ]
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: [
  #     'run', 
  #     'jobs',
  #     'execute',
  #     'dvt',
  #     '--region=us-central1'
  #   ]
  # - name: 'python:3.7'  # Or another suitable image
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #     - CREATE OR REPLACE TABLE bigquery-antipattern-test.antipattern_test_data.dvt_set AS (
  #     - SELECT * FROM `bigquery-antipattern-test.antipattern_test_data.dvt_results` WHERE validation_status != "success"
  #     - )

  # - name: 'python:3.7'  # Or another suitable image
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       if [[ $(bq show --format=prettyjson bigquery-antipattern-test.antipattern_test_data.dvt_set | jq '.totalRows') -gt 0 ]]; then
  #         echo "Table has results, failing the build"
  #         exit 1
  #       else
  #         echo "Table is empty, build success"
  #       fi

options:
  logging: CLOUD_LOGGING_ONLY



