package com.google.zetasql.toolkit.antipattern.parser;

import com.google.zetasql.LanguageOptions;
import com.google.zetasql.Parser;
import com.google.zetasql.parser.ASTNodes;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class IdentifySelfJoinTest {

    LanguageOptions languageOptions;

    @Before
    public void setUp() {
        languageOptions = new LanguageOptions();
        languageOptions.enableMaximumLanguageFeatures();
        languageOptions.setSupportsAllStatementKinds();
    }

    @Test
    public void selfJoinNormalTest() {
        String expected = "Instead of using a self-join at line 9, use a window (analytic) function to reduce the number of additional bytes that are generated by the query.";
        String query =
                        "SELECT \n" +
                        "    t1.dt,\n" +
                        "    t1.taxi_id,\n" +
                        "    t1.ct,\n" +
                        "    t2.ct ct_prev_day\n" +
                        "  FROM \n" +
                        "    `bigquery-public-data.chicago_taxi_trips.taxi_trips` t1\n" +
                        "  LEFT JOIN\n" +
                        "    `bigquery-public-data.chicago_taxi_trips.taxi_trips` t2 \n" +
                        "      ON DATE(t2.dt) = DATE(t1.dt) - INTERVAL 1 DAY\n" +
                        "      AND t1.taxi_id = t2.taxi_id\n" +
                        "  ORDER BY\n" +
                        "    dt desc,\n" +
                        "    taxi_id desc\n" +
                        "  ;\n";
        ASTNodes.ASTStatement parsedQuery = Parser.parseStatement(query, languageOptions);
        String recommendations = (new IdentifySelfJoin().run(parsedQuery, query));
        assertEquals(expected, recommendations);
    }
    @Test
    public void subQuerySelfJoinTest() {
        String expected = "Instead of using a self-join at line 9, use a window (analytic) function to reduce the number of additional bytes that are generated by the query.";
        String query =
                "SELECT \n" +
                        "    t1.dt,\n" +
                        "    t1.taxi_id,\n" +
                        "    t1.ct,\n" +
                        "    t2.ct ct_prev_day\n" +
                        "  FROM \n" +
                        "    `bigquery-public-data.chicago_taxi_trips.taxi_trips` t1\n" +
                        "  LEFT JOIN\n" +
                        "    (select * from `bigquery-public-data.chicago_taxi_trips.taxi_trips`) t2 \n" +
                        "      ON DATE(t2.dt) = DATE(t1.dt) - INTERVAL 1 DAY\n" +
                        "      AND t1.taxi_id = t2.taxi_id\n" +
                        "  ORDER BY\n" +
                        "    dt desc,\n" +
                        "    taxi_id desc\n" +
                        "  ;\n";
        ASTNodes.ASTStatement parsedQuery = Parser.parseStatement(query, languageOptions);
        String recommendations = (new IdentifySelfJoin().run(parsedQuery, query));
        assertEquals(expected, recommendations);
    }

    @Test
    public void nestedJoinTest() {
        String expected = "Instead of using a self-join at line 11, use a window (analytic) function to reduce the number of additional bytes that are generated by the query.";
        String query =
                "SELECT \n" +
                        "  date(t1.trip_start_timestamp) dt,\n" +
                        "  COUNT(DISTINCT t1.unique_key) ct,\n" +
                        "  SUM(t2.ct) ct_month\n" +
                        "FROM \n" +
                        "  `bigquery-public-data.chicago_taxi_trips.taxi_trips` t1\n" +
                        "LEFT JOIN\n" +
                        "  (SELECT \n" +
                        "    FORMAT_DATE(\"%Y-%m\", trip_start_timestamp) month, \n" +
                        "    COUNT(DISTINCT unique_key) ct\n" +
                        "  FROM `bigquery-public-data.chicago_taxi_trips.taxi_trips`\n" +
                        "  GROUP BY month\n" +
                        "  ) t2 \n" +
                        "    ON month = FORMAT_DATE(\"%Y-%m\", t1.trip_start_timestamp)\n" +
                        "WHERE\n" +
                        "  FORMAT_DATE('%Y-%m', t1.trip_start_timestamp) = '2023-02'\n" +
                        "  AND t2.month = '2023-02'\n" +
                        "GROUP BY\n" +
                        "  dt\n" +
                        "ORDER BY\n" +
                        "  dt desc";
        ASTNodes.ASTStatement parsedQuery = Parser.parseStatement(query, languageOptions);
        String recommendations = (new IdentifySelfJoin().run(parsedQuery, query));
        assertEquals(expected, recommendations);
    }

    @Test
    public void newTest() {
        String expected = "";
        String query =
                "SELECT\n" +
                        "    t1.col1\n" +
                        "FROM \n" +
                        "    table1 t1 \n" +
                        "JOIN \n" +
                        "    table2 t2 on t1.col1 = t2.col2\n" +
                        "UNION ALL\n" +
                        "SELECT\n" +
                        "    t2.col1\n" +
                        "FROM \n" +
                        "    table2 t2 \n" +
                        "JOIN \n" +
                        "    table3 t3 on t1.col1 = t2.col2";
        ASTNodes.ASTStatement parsedQuery = Parser.parseStatement(query, languageOptions);
        String recommendations = (new IdentifySelfJoin().run(parsedQuery, query));
        assertEquals(expected, recommendations);
    }

}