name: publish-docker-image-on-release
run-name: publish docker image on release
on:
  push:
    branches: [wf_onrealeas]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn package jib:dockerBuild -DskipTests
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        ls
        gh release upload v1.0.0.1 ./bigquery-antipattern-recognition/target/bigquery-antipattern-recognition-1.0.0.jar
        
