name: publish-docker-image-on-release
run-name: publish docker image on release
on:
  release:
    types: [published]
    branches: [main, wf_onrealeas]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish docker image and jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo RELEASE_VERSION
        
