name: publish-docker-image-on-release
run-name: publish docker image on release
release:
  types: [published]
  branches: [main, wf_onrealeas]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn package jib:dockerBuild -DskipTests
        docker tag bigquery-antipattern-recognition ghcr.io/googlecloudplatform/bigquery-antipattern-recognition:latest
        docker push ghcr.io/googlecloudplatform/bigquery-antipattern-recognition:latest
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        cp ./bigquery-antipattern-recognition/target/bigquery-antipattern-recognition-1.0.0-jar-with-dependencies.jar ./bigquery-antipattern-recognition/target/bigquery-antipattern-recognition.jar
        gh release upload RELEASE_VERSION ./bigquery-antipattern-recognition/target/bigquery-antipattern-recognition.jar
        
