name: learn-github-actions
run-name: build on telease
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: mvn clean package jib:dockerBuild -DskipTests
